# Generated by Django 6.1 on 2026-09-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
